AWSTemplateFormatVersion: 2010-09-09
Description: Template of an EC2 instance in a VPC(subnet,route table etc) reachable by icmp. Test product.
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W60
            reason: "VPC doesn't need flow log"
    Properties:
      CidrBlock: 172.32.0.0/16
      Tags:
        - Key: Name
          Value: TemplateVPC
  MySubnet:
    Type: AWS::EC2::Subnet
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W33
            reason: "Subnet needs to be publically accessible"
    Properties:
      CidrBlock: 172.32.0.0/20
      MapPublicIpOnLaunch: True
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: TemplatePublicSubnet
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: VPC Internet Gateway
  MyVPCInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MyInternetGateway
      VpcId: !Ref MyVPC
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: MyRoutetable
  MyRoute:
    Type: AWS::EC2::Route
    DependsOn:
      - MyVPCInternetGatewayAttachment
    Properties:
      RouteTableId: !Ref MyRouteTable
      GatewayId: !Ref MyInternetGateway
      DestinationCidrBlock: 0.0.0.0/0
  MySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MyRouteTable
      SubnetId: !Ref MySubnet
  MyEC2Instance:
    Type: AWS::EC2::Instance
    DependsOn:
      - MyRoute
      - MySubnetRouteTableAssociation
    Properties:
      ImageId: ami-0a8dc52684ee2fee2
      InstanceType: t2.micro
      SubnetId: !Ref MySubnet
