AWSTemplateFormatVersion: 2010-09-09
Description: A sample template for creating our first stack.
Resources:
  SampleEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09693313102a30b2c
      InstanceType: t2.micro
      Tags:
        - 
          Key: Name
          Value: "SampleInstance"
          
  SampleQueue: 
    Type: AWS::SQS::Queue

  SampleTopic: 
    Type: AWS::SNS::Topic
      